### PR TITLE
Create index.d.ts typings file

### PR DESCRIPTION
**Pull request by dannycochran**
I've done my best to draw out typings for the exported functionality -- but I have not tested every function, so it's possible there's some mistakes.

### CODE REVIEW

**Comment by dannycochran** [comment]
@ariabuckles any chance I can get a review on this?

**Comment by ariabuckles** [comment]
@dannycochran sorry, life's been a lot lately and I haven't had time to get back to simple-markdown things >_<. Thank you for submitting this! I'll do my best to look over it and get back to other issues on here soon.

I actually have some local work for flow.js type definitions, so hopefully that helps in reviewing this and potentially unifying definitions in the future ^_^.

**Comment by hampustagerud** [comment]
@ariabuckles any update on this? 🙂 We are looking to use this at my company but since we use typescript typings is always appreciated. I would of course like help out if that is needed, the typings work fine locally but might need some work? Anyway, it would be nice to have typings bundled with the library instead of having to copy the file.

**Comment by ariabuckles** [comment]
Ah sorry @hampustagerud and @dannycochran !

Before publishing this change I'd like to:

1. make the types the same as those used for Flow (mostly for ease of me checking correctness & for docs)
2. make sure the types are reasonably well-supported (for flow, the whole tests + code is type checked for some baseline confidence that the types are working; I'll see if I can get something like that set up for typescript).

I haven't used typescript yet (though I've been meaning to!) so it might take me a bit of time, but I'll try to prioritize this within the next couple weeks.

**Comment by hampustagerud** [comment]
Sounds good, thank you for looking into this! Let me know if you need any help with this 🙂

**Comment by ariabuckles** [comment]
Thanks! I'll try to get a prototype out and could definitely use help testing it once I do!

**Comment by ariabuckles** [comment]
@dannycochran a very belated thanks for adding these types!

I used these as a base to try to unify the flow and typescript types; I'm planning to merge this and then modify it to match the flow types; hope that's all right with you.

**Comment by ariabuckles** [comment]
@hampustagerud I just published a beta v0.7.0 to npm as `simple-markdown@next` with types in `simple-markdown.d.ts`, that match the flow types and are checked against simple-markdown.js by typescript.

Could you try that out and let me know what problems you find (or if they work for you)? I'll promote that version to the latest release after that (or after a bit of time if you don't have time to try it soon :) ).

Thanks for the ping on this and for the help if you are able!

**Pull request merged**
